name: ig-imports-api

services:
  backend:
    container_name: igimports-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - igimports-network
      - ig-imports_default

networks:
  igimports-network:
    name: igimports-network
    external: true
  ig-imports_default:
    name: ig-imports_default
    external: true
